### ISSUE TITLE
Akka-Http fails to compile with Scala 2.13.0-M3

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1916]
https://jenkins.akka.io:8498/job/akka-http-nightly/31/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.13.0-M3/console

A bunch of compilation errors wrt default arguments and then (probably) some type inference issues around parsers.
