### PR TITLE
Fix compilation error on Scala 2.12

### PR DESCRIPTION
**Pull request by johanandren**

### CODE REVIEW

File: docs/src/test/scala/docs/http/scaladsl/server/directives/DebuggingDirectivesExamplesSpec.scala [hunk 1]
```diff
@@ -130,7 +130,7 @@ class DebuggingDirectivesExamplesSpec extends RoutingSpec {
     }
     def printResponseTime(log: LoggingAdapter) = {
       val requestTimestamp = System.nanoTime
-      akkaResponseTimeLoggingFunction(log, requestTimestamp)(_)
+      akkaResponseTimeLoggingFunction(log, requestTimestamp) _
```
Comment (raboof) [inline docs/src/test/scala/docs/http/scaladsl/server/directives/DebuggingDirectivesExamplesSpec.scala]: Hmm does this also work on 2.12.8? seemed this was changed intentionally at https://github.com/akka/akka-http/pull/2305/files#diff-d4736e778f9a72c660d7563af6fd6f6a

Comment (johanandren) [reply docs/src/test/scala/docs/http/scaladsl/server/directives/DebuggingDirectivesExamplesSpec.scala]: I had to change it to this to make it compile on 2.12.8

Comment (jlprat) [reply docs/src/test/scala/docs/http/scaladsl/server/directives/DebuggingDirectivesExamplesSpec.scala]: mmm that is weird... It was a warning and the builds passed...

Comment (johanandren) [reply docs/src/test/scala/docs/http/scaladsl/server/directives/DebuggingDirectivesExamplesSpec.scala]: That diff does the same as this?

Comment (jlprat) [reply docs/src/test/scala/docs/http/scaladsl/server/directives/DebuggingDirectivesExamplesSpec.scala]: Oooopssss I think coffee really didn't kick in yet.... It's the same change indeed

Comment (raboof) [reply docs/src/test/scala/docs/http/scaladsl/server/directives/DebuggingDirectivesExamplesSpec.scala]: oh huh indeed

Comment (raboof) [reply docs/src/test/scala/docs/http/scaladsl/server/directives/DebuggingDirectivesExamplesSpec.scala]: ah, this is the backport, sorry...
