### ISSUE TITLE
akka-http-testkit 10.1.7 missing classes when instantiating WSProbe

### ISSUE THREAD

**Issue by evbo** [akka/akka-http#2428]
I just upgraded from `akka-http-testkit` version `10.1.5` to `10.1.7` (`com.typesafe.akka:akka-http-testkit_2.12:10.1.7:jar`) and when I try to instantiate a `WSProbe()` I get the following error:

here's how I instantiate it (works in `10.1.5`):
```
val wsClient = WSProbe()
```

Error run from intellij:
```
A needed class was not found. This could be due to an error in your runpath. Missing class: akka/stream/testkit/TestSubscriber$
java.lang.NoClassDefFoundError: akka/stream/testkit/TestSubscriber$
	at akka.http.scaladsl.testkit.WSProbe$$anon$1.<init>(WSProbe.scala:107)
	at akka.http.scaladsl.testkit.WSProbe$.apply(WSProbe.scala:106)
...
```
Error run from sbt:
```
[info]   Cause: java.lang.ClassNotFoundException: akka.stream.testkit.TestSubscriber$
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info]   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[info]   at akka.http.scaladsl.testkit.WSProbe$$anon$1.<init>(WSProbe.scala:107)
[info]   at akka.http.scaladsl.testkit.WSProbe$.apply(WSProbe.scala:106)

```

I currently use the following `Test` dependencies:
```
  "org.scalatest" %% "scalatest" % Dependencies.scalaTestVersion % Test,
  "com.typesafe.akka" %% "akka-testkit" % "2.5.21" % Test,
  "com.typesafe.akka" %% "akka-http-testkit" % "10.1.5" % Test
```

Does the latest version require more dependencies [than currently documented](https://doc.akka.io/docs/akka-http/current/routing-dsl/testkit.html#dependency)?

**Comment by jrudolph** [comment]
Yes, indeed, it seems it's not properly documented.

Try adding `akka-stream-testkit` instead of (or in addition) to `akka-testkit`.

**Comment by jrudolph** [comment]
@jlprat, seems we missed updating the docs in #2263.

**Comment by jlprat** [comment]
You are right, I think we mentioned in the release notes, but probably not in the docs. I can add it later today :)

**Comment by jlprat** [comment]
Looks like is done on master already: https://github.com/akka/akka-http/blob/master/docs/src/main/paradox/routing-dsl/testkit.md

I can add an extra note in there

**Comment by jrudolph** [comment]
> Looks like is done on master already: [/docs/src/main/paradox/routing-dsl/testkit.md@`master`](https://github.com/akka/akka-http/blob/master/docs/src/main/paradox/routing-dsl/testkit.md)

Ah, missed that as well. We should setup nightly docs somewhere.

**Comment by jrudolph** [comment]
Better documentation will come with 10.1.8.
