### ISSUE TITLE
failed: compilation error in Multipart

### ISSUE THREAD

**Issue by patriknw** [akka/akka-http#1952]
https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.0-against-akka-master-on-2.12/48/

```
[error] /home/jenkins/workspace/workspace/akka-http-nightly-release-10.0-against-akka-master-on-2.12/akka-http-core/src/main/scala/akka/http/scaladsl/model/Multipart.scala:294:36: type mismatch;
[error]  found   : akka.stream.javadsl.Source[_$9,AnyRef] where type _$9 <: akka.http.javadsl.model.Multipart.General.BodyPart.Strict
[error]  required: akka.stream.javadsl.Source[akka.http.javadsl.model.Multipart.General.BodyPart.Strict,AnyRef]
[error] Note: _$9 <: akka.http.javadsl.model.Multipart.General.BodyPart.Strict, but class Source is invariant in type Out.
[error] You may wish to define Out as +Out instead. (SLS 4.5)
[error]         super.getParts.asInstanceOf[JSource[_ <: jm.Multipart.General.BodyPart.Strict, AnyRef]]
[error] 
```

Perhaps due to https://github.com/akka/akka/pull/24575 ?

**Comment by patriknw** [comment]
same with 2.11: https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.0-against-akka-master-on-2.11/47/consoleFull

**Comment by raboof** [comment]
Should we backport this to 10.0? (#2049)

**Comment by johanandren** [comment]
Is 10.0 even working with Akka 2.5?

**Comment by ktoso** [comment]
Yes it should, and did work since 10. required only 2.4 things, and 2.5 mostly just adds stuff -- i.e. backwards compatible.

**Comment by ktoso** [comment]
Though we should push people to use 10.1, since upgrading is easy and pretty riskless
